name = "termis-backyard"
uuid = "316e62c2-ef56-46d6-8ff6-b27ca319ed4d"
repo = " git@github.com:termi-official/termis-backyard.git"

[packages]
27d9367a-5072-424e-9c5f-fe582399bac3 = { name = "FerriteOperators", path = "F/FerriteOperators" }
51611a6c-7c63-4cd2-9a52-92f780132403 = { name = "FastIterativeMethod", path = "F/FastIterativeMethod" }
69a0a054-a29c-4d77-8818-cd7ec12cfcdc = { name = "FerriteMultigrid", path = "F/FerriteMultigrid" }
909927c2-98d5-4a67-bba9-79f03a9ad49b = { name = "Thunderbolt", path = "T/Thunderbolt" }
f2515952-d4b9-4d12-b726-4cc023e03d34 = { name = "FerriteDiffEq", path = "F/FerriteDiffEq" }
